name: Manjei Library CD

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.92.1/hugo_0.92.1_Linux-64bit.tar.gz
          tar -xzvf hugo_0.92.1_Linux-64bit.tar.gz
          chmod +x ./hugo

      - name: Build site
        run: |
          cd ./library
          HUGO_ENV="production" ../hugo

      - name: Build and Push Image
        uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: br-com-manjei-library
          heroku_email: lazarodm@gmail.com
          usedocker: true

